services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASS}@db:${DB_PORT}/${DB_NAME}?schema=public
      NODE_ENV: production
      PORT: 8000
    expose:
      - 8000
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
      storage:
        condition: service_healthy

  db:
    image: postgres:17.4-alpine3.21
    restart: always
    user: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    expose:
      - 5432
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  storage:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z-cpuv1
    expose:
      - 9000
      - 9001
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - storage_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: [ "CMD", "mc", "ready", "local" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data:
  storage_data:
